library(tidyverse)
library(reshape2)
library(dplyr)
library(ggplot2)
library(scales)

## Clear workspace
rm(list=ls())

## Read in .csv file
data<-read_csv("tidy_tuesday_week2.csv",col_names=TRUE)

## Replace all NAs with 0
data[is.na(data)] <- 0

## Change year coloumn to character type
data$year<-as.character(data$year)

## Average all numeric columns
#avgdf<-data %>% group_by(year) %>% summarise_if(is.numeric, mean)

## Melt data frame
dfm<-melt(data, id.vars="year")

## Get top 100 salaries
top100<-arrange(dfm, desc(value)) %>% head(n=100)

## Top 100 salaries, size of point = amount of salary
A<-ggplot(top100, aes(x=year, y=variable, color=variable)) +
  geom_jitter(aes(alpha=0.8, size=value)) +
  ylab("Position") +
  xlab("Year") +
  theme(legend.position="none")

pdf("scatter.year.position.pdf")
plot(A)
dev.off()

## All salaries broken down by year
B<-ggplot(dfm, aes(x=year, y=value, color=year)) +
  geom_jitter(aes(alpha=0.5)) +
  theme(legend.position="none") +
  scale_y_continuous(labels = dollar) +
  ylab("Salary") +
  xlab("Year")

pdf("scatter.year.salary.pdf")
plot(B)
dev.off()

## Count of top 100 salaries, broken down by position & year
C<-ggplot(top100, aes(variable, fill=variable)) +
  geom_histogram(stat="count") +
  facet_wrap(~ year) +
  theme(legend.position="none",axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("Position") +
  ylab("Count")

pdf("count.top100.pdf")
plot(C)
dev.off()
