library(readxl)
library(tidyverse)

### Read in sheet from Excel file
beer_data <- read_excel("week15_beers.xlsx", sheet = "beers")

### Select style column, group,
### count the number of times each style appears,
### reorder in descending order, get first 10 lines,
### reorder by percent
style_count <- beer_data %>%
  select(style) %>%
  group_by(style) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(10) %>%
  mutate(pct = (count/2400)*100) %>%
  transform(style = reorder(style, pct))

### Plot bar plot
A <- ggplot(style_count) +
  geom_bar(aes(x = style, y = pct, fill = style), stat = "identity") +
  geom_text(aes(x=style, y=pct, label=paste(round(pct,2),"%")), hjust = -0.25) +
  coord_flip() +
  theme(legend.position="none", axis.title = element_blank(), axis.text=element_text(size = 13), panel.background = element_blank(), panel.grid.major.x = element_line(colour = 'gray', linetype = 'dashed'), axis.ticks=element_blank(), plot.title=element_text(size = 20, hjust = 0.5)) +
  scale_y_continuous(limit=c(0,22),labels = function(x) paste0(x, "%")) +
  scale_fill_brewer(palette = "BrBG") +
  ggtitle("Top 10 Styles of Beer")

### Save plot to file
png("top.10.style.png")
plot(A)
dev.off()
