library(reshape2)
library(tidyverse)

### Clear workspace
rm(list=ls())

### Read in data
data<-read_csv("star.wars.csv")

### Clean up data & move to new data frame
### Most of the clean up is renaming columns
data1<-rename_at(data, 4, ~"Ep1_seen") %>% rename_at(5, ~"Ep2_seen") %>% rename_at(6, ~"Ep3_seen") %>% rename_at(7, ~"Ep4_seen") %>% rename_at(8, ~"Ep5_seen") %>% rename_at(9, ~"Ep6_seen") %>% rename_at(10, ~"Rating_6") %>% rename_at(11, ~"Rating_5") %>% rename_at(12, ~"Rating_4") %>% rename_at(13, ~"Rating_3") %>% rename_at(14, ~"Rating_2") %>% rename_at(15, ~"Rating_1") %>% rename_at(16, ~"Han_Solo") %>% rename_at(17, ~"Luke_Skywalker") %>% rename_at(18, ~"Princess_Leia") %>% rename_at(19, ~"Anakin_Skywalker") %>% rename_at(20, ~"Obi_Wan") %>% rename_at(21, ~"Emperor_Palpatine") %>% rename_at(22, ~"Darth_Vader") %>% rename_at(23, ~"Lando_Calrissian") %>% rename_at(24, ~"Boba_Fett") %>% rename_at(25, ~"C3PO") %>% rename_at(26, ~"R2D2") %>% rename_at(27, ~"Jar_Jar_Binks") %>% rename_at(28, ~"Padme_Amidala") %>% rename_at(29, ~"Yoda")

### Remove first row (second header row)
data1<-data1[-1,]

### Select character & gender columns
### melt data frame using Gender as id
### drop NAs, group & tally
### ungroup, change values into factor,
### remove the underscores from character names
char_rating_gender<-select(data1, Han_Solo, Luke_Skywalker, Princess_Leia, Anakin_Skywalker, Obi_Wan, Emperor_Palpatine, Darth_Vader, Lando_Calrissian, Boba_Fett, C3PO, R2D2, Jar_Jar_Binks, Padme_Amidala, Yoda, Gender) %>% melt(id.vars="Gender") %>% drop_na() %>% group_by(Gender, variable, value) %>% tally() %>% ungroup() %>% mutate(value = factor(value, levels=c("Very favorably", "Somewhat favorably", "Neither favorably nor unfavorably (neutral)", "Somewhat unfavorably", "Very unfavorably", "Unfamiliar (N/A)")), variable=gsub("_", " ", variable))

### Create plot
A<-ggplot(char_rating_gender) +
  geom_point(aes(x = value, y = variable, color=value, size=n)) +
  geom_text(aes(x = value, y = variable, label=n)) +
  facet_wrap(~Gender) +
  theme(legend.position="bottom", legend.title=element_blank(), legend.text=element_text(size=12), axis.title=element_blank(), axis.text.x=element_blank(), axis.text.y = element_text(size=15, face="bold"), axis.ticks=element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.text.x = element_text(size = 12), plot.title=element_text(size=20, hjust = 0.5)) +
  scale_size_continuous(range = c(10, 22), guide = 'none') +
  scale_color_manual(values=c("#00b3ca","#7dd0b6", "#d2b29b", "#e38690", "#f69256", "#ead98b")) +
  guides(colour = guide_legend(override.aes = list(size=10))) +
  scale_y_discrete(limits = unique(rev(char_rating_gender$variable))) +
  ggtitle("Character Ratings")

### Save plot to file
png("char.rating.gender.png", height=850, width=850)
plot(A)
dev.off()

### Select character $ gender columns
### melt data frame using Gender as id
### drop NAs, group & tally
### ungroup, change values into factor,
### remove the underscores from character names
char_rating<-select(data1, Han_Solo, Luke_Skywalker, Princess_Leia, Anakin_Skywalker, Obi_Wan, Emperor_Palpatine, Darth_Vader, Lando_Calrissian, Boba_Fett, C3PO, R2D2, Jar_Jar_Binks, Padme_Amidala, Yoda, Gender) %>% melt(id.vars="Gender") %>% drop_na() %>% select(-Gender) %>% group_by(variable, value) %>% tally() %>% ungroup() %>% mutate(value = factor(value, levels=c("Very favorably", "Somewhat favorably", "Neither favorably nor unfavorably (neutral)", "Somewhat unfavorably", "Very unfavorably", "Unfamiliar (N/A)")), variable=gsub("_", " ", variable))

B<-ggplot(char_rating) +
  geom_point(aes(x = value, y = variable, color=value, size=n)) +
  geom_text(aes(x = value, y = variable, label=n)) +
  theme(legend.position="bottom", legend.title=element_blank(), legend.text=element_text(size=12), axis.title=element_blank(), axis.text.x=element_blank(), axis.text.y = element_text(size=15, face="bold"), axis.ticks=element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.text.x = element_text(size = 12), plot.title=element_text(size=20, hjust = 0.5)) +
  scale_size_continuous(range = c(10, 22), guide = 'none') +
  scale_color_manual(values=c("#00b3ca","#7dd0b6", "#d2b29b", "#e38690", "#f69256", "#ead98b")) +
  guides(colour = guide_legend(override.aes = list(size=10))) +
  scale_y_discrete(limits = unique(rev(char_rating$variable))) +
  ggtitle("Character Ratings")

png("char.rating.png", height=850,width=675)
plot(B)
dev.off()
