library(reshape2)
library(tidyverse)

### Clear workspace
rm(list=ls())

### Read in data
data<-read_csv("star.wars.csv")

### Clean up data & move to new data frame
### Most of the clean up is renaming columns
data1<-rename_at(data, 4, ~"Ep1_seen") %>% rename_at(5, ~"Ep2_seen") %>% rename_at(6, ~"Ep3_seen") %>% rename_at(7, ~"Ep4_seen") %>% rename_at(8, ~"Ep5_seen") %>% rename_at(9, ~"Ep6_seen") %>% rename_at(10, ~"Rating_6") %>% rename_at(11, ~"Rating_5") %>% rename_at(12, ~"Rating_4") %>% rename_at(13, ~"Rating_3") %>% rename_at(14, ~"Rating_2") %>% rename_at(15, ~"Rating_1") %>% rename_at(16, ~"Han_Solo") %>% rename_at(17, ~"Luke_Skywalker") %>% rename_at(18, ~"Princess_Leia") %>% rename_at(19, ~"Anakin_Skywalker") %>% rename_at(20, ~"Obi_Wan") %>% rename_at(21, ~"Emperor_Palpatine") %>% rename_at(22, ~"Darth_Vader") %>% rename_at(23, ~"Lando_Calrissian") %>% rename_at(24, ~"Boba_Fett") %>% rename_at(25, ~"C-3PO") %>% rename_at(26, ~"R2D2") %>% rename_at(27, ~"Jar_Jar_Binks") %>% rename_at(28, ~"Padme_Amidala") %>% rename_at(29, ~"Yoda")

### Remove first row (second header row)
data1<-data1[-1,]

### Select column with highest rated movie & Gender, drop NAs
### Change values to actual movie names
Fave_movie_by_gender<-select(data1, Rating_6, Gender) %>% drop_na() %>% mutate(Rating_6 = str_replace(Rating_6, "1", "Star Wars: Episode I The Phantom Menace"), Rating_6 = str_replace(Rating_6, "2", "Star Wars: Episode II Attack of the Clones"), Rating_6 = str_replace(Rating_6, "3", "Star Wars: Episode III Revenge of the Sith"), Rating_6 = str_replace(Rating_6, "4", "Star Wars: Episode IV A New Hope"), Rating_6 = str_replace(Rating_6, "5", "Star Wars: Episode V The Empire Strikes Back"), Rating_6 = str_replace(Rating_6, "6", "Star Wars: Episode VI Return of The Jedi"))

### Create plot
A<-ggplot(Fave_movie_by_gender) +
  geom_bar(aes(x=Rating_6, y=..count.., fill=Gender), position="dodge", stat="count") +
  geom_text(aes(x=Rating_6, y=..count.., fill=Gender, label=..count..), position=position_dodge(width=1), stat="count", vjust = -0.5) +
  xlab("Favorite Movie") +
  theme(legend.position="bottom", legend.title=element_blank(),  axis.text.y=element_blank(), axis.ticks=element_blank(), axis.title=element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.text.x = element_text(size=12), plot.title=element_text(size=20, hjust = 0.5)) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 11)) +
  ggtitle("Favorite Star Wars Movie") +
  scale_fill_manual(values=c("#ffb3ff", "#99ebff"))

### Save plot to file
png("fave.movie.gender.png", height=600, width=600)
plot(A)
dev.off()
