library(reshape2)
library(tidyverse)

### Clear workspace
rm(list=ls())

### Read in data file
data<-read_csv("acs2015_county_data.csv", col_names=TRUE)

### Subset to find all counties in Illinois
### Select columns of interest
### Calculate percent for gender
### Drop columns not needed for final graphic
statedata<-subset(data, State == "Illinois") %>% select(County, TotalPop, Men, Women, Hispanic, White, Black, Native, Asian, Pacific) %>% mutate(Men.total = (Men/TotalPop)*100, Women.total = (Women/TotalPop)*100) %>% select(-Men, -Women, -TotalPop)

### Melt data frame
dfm<-melt(statedata, id.vars=c("County"))

### Assign variable for facet_wrap
dfm$var<-ifelse(dfm$variable == "Men.total" | dfm$variable == "Women.total", "Gender", "Race")

### Plot data
A<-ggplot(dfm) +
  geom_jitter(data=dfm, aes(y=reorder(County, desc(County)), x=variable, size=value, color=variable), alpha=0.8) +
  facet_wrap(~var, scale="free_x") +
  labs(color="", size="Percent of Population") +
  theme(legend.position="bottom", axis.text.x=element_blank(), axis.title.x=element_blank(), axis.ticks.x=element_blank()) +
  ylab("County")

### Save to file
png("IL.pop.png", height=1000, width=800)
plot(A)
dev.off()
