library(tidyverse)
library(reshape2)

### Clear workspace
rm(list=ls())

### Read in data file
data<-read_csv("acs2015_county_data.csv", col_names=TRUE)

### Find top 10 states by average county income
top10inc<-group_by(data, State) %>% summarise(num = n(), total = sum(Income)) %>% mutate(Avg = total/num) %>% arrange(desc(Avg)) %>% top_n(10,Avg)

### Get income of top 10 states
Income<-select(data, State, County, Income) %>% subset(State %in% top10inc$State)
### Calculate number of people at poverty level for top 10 states
Poverty<-select(data, State, County, TotalPop, Poverty) %>% mutate(Poverty.total = TotalPop * (Poverty/100)) %>% subset(State %in% top10inc$State) %>% select(-Poverty)

### Join income & poverty data frames
df<-left_join(Income, Poverty, by=c("State", "County")) %>% mutate(Poverty = (Poverty.total/TotalPop) * 100) %>% select(-Poverty.total, -TotalPop, -County) %>% subset(State %in% top10inc$State)

### Melt data frame
dfm<-melt(df)

### Set names for facet_wrap labels
names<-c(`Poverty` = "Poverty (Percent of Population)", `Income` = "Average Income of Counties (US Dollar)")

### Plot data
A<-ggplot(dfm) +
  geom_boxplot(aes(x=fct_rev(State), y=value, fill=State)) +
  facet_wrap(~variable, scale="free_x", ncol=1, labeller = as_labeller(names)) +
  coord_flip() +
  xlab("") +
  scale_fill_manual(values=c("#9dc6d8", "#00b3ca", "#7dd0b6","#1d4e89","#d2b29b", "#e38690", "#f69256","#ead98b","#965251","#c6cccc")) +
  theme(legend.position="none", axis.text.y=element_text(size=12), axis.title.x=element_blank(), strip.text.x = element_text(size = 12)) +
  scale_y_continuous(labels = scales::comma)

### Save graphic to file
png("top.by.income.income.poverty.png", width=600, height=600)
plot(A)
dev.off()
