library(RColorBrewer)
library(readxl)
library(reshape2)
library(tidyverse)
library(scales)

## Clear workspace
rm(list=ls())

## Read in excel file
data<-read_excel("global_mortality.xlsx")

## Remove (%) from column names
names(data) <- str_trim(str_remove_all(names(data), "[[:punct:]]"))

## Subset data by year (2016) & country (Guatemala)
datan<-subset(data, year == 2016) %>% subset(countrycode == "GTM")

## Remove countrycode & year column
datan<-select(datan, -(countrycode:year))

## Melt data frame
dfm<-melt(datan)

## Replace all NAs with 0
dfm[is.na(dfm)] <- 0

## Find number of unique variables (diseases)
colourCount = length(unique(dfm$variable))

## Choose color palettes
getPalette = colorRampPalette(brewer.pal(8, "Dark2"))

## Create plot
A<-ggplot(dfm, aes(reorder(variable,value), value, fill=variable)) +
  geom_bar(stat="identity") +
  coord_flip() +
  scale_y_continuous(breaks=seq(0,30,by=5), labels=function(x) paste0(x,"%")) +
  geom_text(data=dfm, aes(variable, value, label=paste(sprintf("%0.2f", round(value, digits = 2)),"%")), hjust=-0.1) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.border = element_blank(), panel.background = element_blank(), legend.position="none") +
  geom_hline(yintercept=c(5,10,15,20), linetype="dotted", color="gray") +
  ylab("") +
  xlab("") +
  scale_fill_manual(values = getPalette(colourCount)) +
  ggtitle("Share of deaths by cause, Guatemala, 2016")

## Save to file
png("Guat.2016.png", height=500, width=600)
plot(A)
dev.off()
