library(ggplot2)
library(plyr)
library(RColorBrewer)
library(readxl)
library(reshape2)
library(tidyverse)

### Clear workspace
rm(list=ls())

### Read in excel file
data<-read_excel("global_mortality.xlsx")

### Set all NAs to 0
data[is.na(data)] <- 0

### Remove (%) from column names
names(data) <- str_trim(str_remove_all(names(data), "[[:punct:]]"))

### Use only data from 2016
datan<-subset(data, year == 2016)

### Read in population csv file
popdata<-read.csv("pop2.csv", header=TRUE)

### Subset original data tibble using countries
### from population data frame
datan2<-subset(datan, country %in% popdata$country)

### Merge population data frame with original data
alldata<-merge(datan2, popdata, by = "country", all = TRUE)

### Remove columns not needed for final graphic
alldata<-select(alldata, -(countrycode:year))

### Calculate percent of total population for each country
alldata$pct<-alldata$population/sum(as.numeric(alldata$population))

### Calculate x axis maximum
alldata$xmax<-cumsum(alldata$pct)

### Calculate x axis minimum
alldata$xmin<-alldata$xmax - alldata$pct

### Set percent & population column to null
alldata$pct<-NULL
alldata$population<-NULL

### Melt from wide to long
dfm<-melt(alldata, id = c("country", "xmin", "xmax"))

### Calculate y maximum
dfm1<-ddply(dfm, .(country), transform, ymax = cumsum(value))

### Calculate y minimum
dfm1 <- ddply(dfm1, .(country), transform, ymin = ymax - value)

### Calculate where county labels will be
dfm1$xtext <- with(dfm1, xmin + (xmax - xmin)/2)
dfm1$ytext <- with(dfm1, ymin + (ymax - ymin)/2)

### Calculate number of unique disease
colourCount = length(unique(dfm$variable))

### RColorBrewer palette
getPalette = colorRampPalette(brewer.pal(12, "Paired"))

### Create plot
A<-ggplot(dfm1, aes(ymin = ymin, ymax = ymax, xmin = xmin, xmax = xmax, fill = variable)) +
  geom_rect() +
  geom_text(aes(x = xtext, y = 105, label = country, angle=45, vjust=1.5, family='Times')) +
  theme(legend.position="bottom", panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.border = element_blank(), panel.background = element_blank(), legend.text=element_text(size=10))+
  labs(x = NULL, y = NULL, fill = NULL) +
  scale_fill_manual(values = getPalette(colourCount)) +
  geom_segment(aes(x=0.4608207, y=0, xend=0.4608207, yend=100)) +
  geom_segment(aes(x=0.4840388, y=0, xend=0.4840388, yend=100)) +
  geom_segment(aes(x=0.6102160, y=0, xend=0.6102160, yend=100)) +
  geom_segment(aes(x=0.6251425, y=0, xend=0.6251425, yend=100)) +
  geom_segment(aes(x=0.6626928, y=0, xend=0.6626928, yend=100)) +
  geom_segment(aes(x=0.7485464, y=0, xend=0.7485464, yend=100)) +
  geom_segment(aes(x=0.4840388, y=0, xend=0.4840388, yend=100)) +
  guides(fill=guide_legend(nrow=5,byrow=TRUE))

### Save plot to file, custom size
png("mosaic.png", height=800, width=1000)
plot(A)
dev.off()
