library(tidyverse)
library(pheatmap)
library(reshape2)
library(RColorBrewer)

## Clear workspace
rm(list=ls())

## Read in .csv file
data<-read.csv("tidy_tuesday_week2.csv", header=TRUE)

## Replace all NAs with 0
data[is.na(data)] <- 0

## Change year coloumn to character type
data$year<-as.character(data$year)

## Average data by position for each year
avgdf<-data %>% group_by(year) %>% summarise_if(is.numeric, mean) %>% as.data.frame

## Function to create matrix but keep row names
matrix.convert<-function(x)
  {
    m<-as.matrix(x[,-1])
    rownames(m)<-x[,1]
    m
  }

## Use matrix function to convert dataframe
dfm<-matrix.convert(avgdf)

## Function to over ride column labels in pheatmap
draw_colnames_45 <- function (coln, gaps, ...) {
    coord = pheatmap:::find_coordinates(length(coln), gaps)
    x = coord$coord - 0.5 * coord$size
    res = textGrob(coln, x = x, y = unit(1, "npc") - unit(3,"bigpts"), vjust = 0.5, hjust = 1, rot = 45, gp = gpar(...))
    return(res)}

assignInNamespace(x="draw_colnames", value="draw_colnames_45",
ns=asNamespace("pheatmap"))

## Color palette
myPalette <- colorRampPalette(rev(brewer.pal(11, "RdYlBu")))

## Plot heat map
pheatmap(dfm, color=colorRampPalette(rev(brewer.pal(11, "RdYlBu")))(100), border_color=NA, cluster_cols=T, cluster_rows=F, filename="pheatmap.tiff", cellwidth=15, cellheight=15, width =4, height=4)
