library(reshape2)
library(tidyverse)

### Clear workspace
rm(list=ls())

### Read in data
data<-read_csv("acs2015_county_data.csv", col_names=TRUE)

### Vector with list of top 10 states by population
top10<-c("California","Texas","Florida","New York","Pennsylvania","Illinois","Ohio","Georgia","North Carolina","Michigan")

### Calculate total number of people for columns of interest
### Select calculated columns
### Group rows by state
### Calculate totals for each column by state
### filter data by vector of states
statedata<-mutate(data, Hispanic.total = Hispanic * (TotalPop/100), White.total = White * (TotalPop/100), Black.total = Black * (TotalPop/100), Native.total = Native * (TotalPop/100), Asian.total = Asian * (TotalPop/100), Pacific.total = Pacific * (TotalPop/100)) %>% select(State, TotalPop, Hispanic.total, White.total, Black.total, Native.total, Asian.total, Pacific.total) %>% group_by(State) %>% summarise(TotalPop = sum(TotalPop), Hispanic = sum(Hispanic.total), White = sum(White.total), Black = sum(Black.total), Native = sum(Native.total), Asian = sum(Asian.total), Pacific = sum(Pacific.total)) %>% filter(State %in% top10)

### Melt data frame
dfm<-melt(statedata, id.vars=c("State", "TotalPop"))

### Plot graphic
A<-ggplot(dfm) +
  geom_point(data=subset(dfm, (value/TotalPop)*100>=0.005), aes(y=reorder(State, TotalPop), x=variable, size=(value/TotalPop)*100, color=variable), alpha=0.8) +
  geom_text(data=subset(dfm, (value/TotalPop)*100>=0.005), aes(x=variable, y=reorder(State, desc(TotalPop)), label=sprintf("%0.2f", round((value/TotalPop)*100, digits = 2)), hjust=.5, vjust=0.5), size=5) +
  theme(legend.position="bottom", legend.title=element_blank(), axis.ticks=element_blank(), axis.title=element_blank(), axis.text.x=element_blank(), axis.text=element_text(size=25), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background=element_blank(), legend.text=element_text(size=12), plot.title = element_text(size=30)) +
  scale_size_continuous(range = c(15, 43), guide = 'none') +
  guides(colour = guide_legend(override.aes = list(size=10), nrow=1)) +
  scale_color_manual(values=c("#9dc6d8", "#00b3ca", "#7dd0b6", "#d2b29b", "#e38690", "#f69256")) +
  ggtitle("Percentage of Race in Population of 10 States")

### Save plot to file
png("top10.pop.png", height=900, width=900)
plot(A)
dev.off()
