library(readxl)
library(tidyverse)

### Read in both sheets from Excel file
beer_data <- read_excel("week15_beers.xlsx", sheet = "beers")
brewery_data <- read_excel("week15_beers.xlsx", sheet = "breweries") %>%
  rename(brewery_id = id)

### Join both data frames by brewery ID,
### count number of beers for each brewery,
### get top 10, & find percent,
### reorder by percent
brewery_count <- left_join(beer_data, brewery_data, by="brewery_id") %>%
  select(name.y) %>%
  group_by(name.y) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(10) %>%
  mutate(pct = (count/2400)*100) %>%
  transform(name.y = reorder(name.y, pct))

### Plot bar graph
A <- ggplot(brewery_count) +
  geom_bar(aes(x=name.y, y=pct, fill=name.y), stat="identity") +
  geom_text(aes(x=name.y, y=pct, label=paste(round(pct,2),"%")), hjust = -0.25) +
  coord_flip() +
  theme(legend.position="none", axis.title = element_blank(), axis.text=element_text(size = 13), panel.background = element_blank(), panel.grid.major.x = element_line(colour = 'gray', linetype = 'dashed'), axis.ticks=element_blank(), plot.title=element_text(size = 20, hjust = 0.5)) +
  scale_y_continuous(limit = c(0,3),labels = function(x) paste0(x, "%")) +
  scale_fill_brewer(palette = "RdGy", direction = -1) +
  ggtitle("Top Ten Breweries")

### Save to file
png("top.10.brewery.png")
plot(A)
dev.off()
