library(readxl)
library(tidyverse)

### Read in both sheets from Excel file
beer_data <- read_excel("week15_beers.xlsx", sheet = "beers")
brewery_data <- read_excel("week15_beers.xlsx", sheet = "breweries")

### Get state column, count each state,
### keep top 10, calculate percent
state_count <- brewery_data %>%
  select(state) %>%
  group_by(state) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(10) %>%
  mutate(pct = (count/548)*100) %>%
  transform(state = reorder(state, pct))

### make bar plot
A <- ggplot(state_count) +
  geom_bar(aes(x = state, y = pct, fill = state), stat="identity") + geom_text(aes(x=state, y=pct, label=paste(round(pct,2),"%")), hjust = -0.25) +
  coord_flip() +
  theme(legend.position="none", axis.title = element_blank(), axis.text=element_text(size = 13), panel.background = element_blank(), panel.grid.major.x = element_line(colour = 'gray', linetype = 'dashed'), axis.ticks=element_blank(), plot.title=element_text(size = 20, hjust = 0.5)) +
  scale_y_continuous(limit = c(0,9.5),labels = function(x) paste0(x, "%")) +
  scale_fill_brewer(palette = "PuOr", direction = -1) +
  ggtitle("Top Ten States by Brewery")

### Save plot to file
png("top.10.state.brewery.png")
plot(A)
dev.off()
