library(readxl)
library(tidyverse)

### Clear workspace
rm(list=ls())

### Read in excel file
data<-read_excel("week6_coffee_chains.xlsx")

### Count total number of Starbucks
count<-filter(data, Brand == "Starbucks") %>% summarise(num = n())

### Filter for all Starbucks
### Rename 'Ownership Type' column
### Group by Ownership Tyoe
### Count each type of Ownership
### Calculate percent of each type of ownership
totalcount<-filter(data, Brand == "Starbucks") %>% rename(Otype = 'Ownership Type') %>% group_by(Otype) %>% summarise(num = n()) %>% mutate(fct = as.factor((num/25249)*100), pct = (num/25249)*100)

### Create plot
A<-ggplot(totalcount) +
  geom_bar(aes(x=Otype, y=pct, fill=fct), stat="identity") +
  geom_text(aes(x=Otype, y=pct, label=paste(round(pct,digits=2),"%")), vjust=-0.85, size=5) +
  theme(legend.position="none", axis.text.y = element_blank(), axis.ticks = element_blank(), axis.title=element_blank(), axis.text.x = element_text(size=15), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), plot.title=element_text(size=28, face="bold", hjust = 0.5)) +
  scale_fill_manual(values=c("#9dc6d8", "#00b3ca", "#7dd0b6", "#1d4e89")) +
  ggtitle("Ownership Type of All Starbucks")

### Save plot to file
png("own.type.png", width=600, height=600)
plot(A)
dev.off()

### Group & count all Starbucks my time zones
totalcount2<-filter(data, Brand == "Starbucks") %>% group_by(Timezone) %>% summarise(num = n()) %>% mutate(fct = as.factor((num/25249)*100), pct = (num/25249)*100)

### Create plot
B<-ggplot(totalcount2) +
  geom_bar(aes(x=Timezone, y=pct, fill=fct), stat="identity") +
  geom_text(aes(x=Timezone, y=pct, label=paste(round(pct,digits=2),"%")), hjust=-0.1) +
  coord_flip() +
  theme(legend.position="none", axis.text.x = element_text(size=20))

### Save graphic to file
png("timezone.png", height=1000, width=1000)
plot(B)
dev.off()

### Split Time zone column to get region column
### Calculate percent of stores in each region
totalcount3<-filter(data, Brand == "Starbucks") %>% select(Timezone) %>% separate(Timezone, into=c("1", "2"), sep=" ") %>% separate(2, into=c("keep","toss"), sep="/") %>% select(keep) %>% group_by(keep) %>% summarise(num = n()) %>% mutate(fct = as.factor((num/25239)*100), pct = (num/25239)*100)

### Create plot
C<-ggplot(totalcount3) +
  geom_bar(aes(x=fct_rev(as_factor(keep)), y=pct, fill=fct), stat="identity") +
  geom_text(aes(x=fct_rev(as_factor(keep)), y=pct, label=paste(round(pct, digits=2),"%")), hjust=-0.1) +
  coord_flip() +
  scale_y_continuous(limits = c(0, 70), expand = c(0, 0)) +
  theme(legend.position="none", axis.text.x = element_blank(), axis.ticks = element_blank(), axis.title=element_blank(), axis.text.y = element_text(size=15), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), plot.title=element_text(size=28, face="bold", hjust = 0.5))

### Save plot to file
png("region.png", height=500, width=500)
plot(C)
dev.off()
