library(tidyverse)

data <- read_csv("comic.data.csv") %>% select(-X1)

#ID <- data %>%
#  select(name, appearances) %>%
#  group_by() %>%
#  summarise(count = n())

### Total percent of appearances by top 10 characters ( < 7%)
N_A <- data %>%
  select(name, appearances) %>%
  arrange(desc(appearances)) %>%
  head(20) %>%
  mutate(pct = (appearances/414802)*100) %>%
  select(pct) %>%
  summarise(count = sum(pct))

### Percent of appearances by top 10 characters
N_A2 <- data %>%
  select(name, appearances, sex) %>%
  arrange(desc(appearances)) %>%
  head(20) %>%
  mutate(pct = (appearances/414802)*100) %>%
  separate(name, into=c("keep", "dump"), sep="\\(") %>%
  select(keep, pct, sex) %>%
  rename(name = keep)

### Find total number of appearances by all characters
total <- data %>%
  select(appearances) %>%
  na.omit() %>%
  summarise(count = sum(appearances))

#N_A2$name <- factor(N_A2$name, levels=N_A2$name[order(N_A2$pct)], ordered=TRUE)

A <- ggplot(N_A2) +
  geom_bar(aes(x = name, y = pct, fill = sex), stat = "identity") +
  geom_text(aes(x = name, y = pct + 0.13, label = round(pct,2)), size=3) +
  coord_polar() +
  theme(legend.position = "bottom",
    legend.title = element_blank(),
    axis.title = element_blank(),
    axis.text.x = element_text(size = 9),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    plot.title = element_text(size = 20, hjust = 0.5)) +
  scale_y_continuous(limits = c(0,1.2)) +
  scale_fill_manual(values = c("#a323a1", "#005295")) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  ggtitle("Top 20 Characters by Appearances (%)")

png("top.20.png")
plot(A)
dev.off()
